# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a5To4cWlY5CoUMMN4XWMMn7WLm-5_pS-
"""

#set time limit
data={}
def read(i):
    filename = 'xlrandom' + str(i) + '.xlsx'
    data['g' + str(i)] = pd.read_excel(filename)
    a=data['g' + str(i)]
    print(a.head(1))
    return a

import time

# Set the time limit in seconds
time_limit = 30  # 30 seconds

start_time = time.time()

# Calculate the end time by adding the time limit to the start time
end_time = start_time + time_limit
import pandas as pd


while time.time() < end_time:
    time.sleep(1)
    c= input("Enter the file you want to read")
    if c=='1' or c=='file1' or c=='f1':
      x=read(1)
    elif c=='2' or c=='file2'or c=='f2':
      x=read(2)
    elif c=='3' or c=='file3'or c=='f3':
      x=read(3)
    elif c=='4' or c=='file4'or c=='f4':
      x=read(3)
    else:
        print("File not found ")