# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a5To4cWlY5CoUMMN4XWMMn7WLm-5_pS-
"""

#create random using foor sta
import numpy as np
from numpy import random
import pandas as pd

for i in range(1, 5):
    arr = ['Arun', 'Akash', 'Sanjay', 'Manu']
    a = np.random.choice(arr, 15, p=[0.5, 0.1, 0.1, 0.3])
    b = random.choice([30, 52, 72, 91, 80, 60], p=[0.1, 0.2, 0.3, 0.1, 0.1, 0.2], size=(15))
    c = random.choice([30, 52, 72, 91, 80, 60], p=[0.1, 0.2, 0.3, 0.1, 0.1, 0.2], size=(15))
    d = random.choice([30, 52, 72, 91, 80, 60], p=[0.1, 0.2, 0.3, 0.1, 0.1, 0.2], size=(15))
    e = random.choice([30, 52, 72, 91, 80, 60], p=[0.1, 0.2, 0.3, 0.1, 0.1, 0.2], size=(15))
    f = random.choice([30, 52, 72, 91, 80, 60], p=[0.1, 0.2, 0.3, 0.1, 0.1, 0.2], size=(15))

    np.random.shuffle(a)
    np.random.shuffle(b)
    np.random.shuffle(c)
    np.random.shuffle(d)
    np.random.shuffle(e)
    np.random.shuffle(f)

    frame = {"Name": a, "English": b, "Math": c, "Physics": d, "Chemistry": e, "Electronics": f}
    df = pd.DataFrame(frame)

    df.to_excel('xlrandom' + str(i) + '.xlsx', index=False)
    df.to_csv('csrandom' + str(i) + '.csv', index=False)